import numpy as np

def calculate_dnn(cloud: np.ndarray) -> float:
    """Calculate the characteristic length scale of the point cloud

    Parameters
    ----------
    cloud: numpy.ndarray
        The point cloud

    Returns
    -------
    float:
        The characteristic length scale
    """
    ...

def smooth_pointcloud(
    cloud: np.ndarray, dnn: float | None, neighborhood_radius: float = 2.0
) -> np.ndarray:
    """Smooth a point cloud which has already been sorted in z

    Perform nearest neighbor smoothing on a pointcloud. If dnn is given,
    the neighborhood radius is calculated from that scale. If dnn is not given
    and neighborhood_radius is given, neighborhood_radius is used. If neither
    are given, dnn is calculated from the cloud. This last option should *only*
    be used if dnn is not going to be used in subsequent calculations (i.e. clustering).

    Parameters
    ----------
    cloud: numpy.ndarray
        The pointcloud to smooth
    dnn: float | None
        The characteristic length scale.
        The general recommendation is to give a dnn value.
    neighborhood_radius: float | None
        The maximum raidal distance between neighbors. The default
        value is 2.0.

    Returns
    -------
    numpy.ndarray
        A new smoothed pointcloud
    """
    ...

def triplet_clustering(
    smoothed_cloud: np.ndarray,
    dnn: float | None,
    triplet_neighborhood_size: int = 19,
    triplet_max_candidates: int = 2,
    triplet_error_cutoff: float = 0.03,
    cluster_scale: float = 0.3,
    min_cluster_size: int = 5,
    linkage: str = "single",
    cluster_distance_threshold: float | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Apply the triplclust algorithm to a smoothed point cloud

    Cluster the points by the triplclust triplet metric

    Parameters
    ----------
    smoothed_cloud: numpy.ndarray
        The smoothed, sorted pointcloud
    dnn: float | None
        If dnn is not None, it is used to calculate the scale factor as cluster_scale * dnn.
        It is generally recommended to provide a dnn value.
    triplet_neighborhood_size: int
        The size of the triplet search neighborhood in points. The default
        value is 19.
    triplet_max_candidates: int
        The maximum of triplet candidates to consider for a point. The default
        value is 2.
    triplet_error_cutoff: float
        The error cutoff for evaluating triplet candidates. The default value
        is 0.03.
    cluster_scale: float
        The scale factor used in the triplet distance metric. If dnn is not None,
        the scale factor is cluster_scale * dnn. The default value is 0.3.
    min_cluster_size: int
        The minimum number of points required for a cluster to be valid. The default
        value is 5.
    linkage: str
        The type of linkage to use in the agglometrive clustering.
        Valid values are "single", "complete", "average", and "median". The default
        value is "single".
    cluster_distance_threshold: float | None
        The cluster distance used as a stopping criterion in the
        hierarchical clustering. If None, the appropriate threshold
        is calculated from the data. The default value is None.

    Returns
    -------
    tuple[numpy.ndarray, numpy.ndarray]
        A set of 1-D integer arrays, where the first is the set of cluster
        labels for each point in the point cloud and the second is the list
        of unique cluster labels. A label of -1 indicates that the point was
        not included in any *valid* cluster.
    """
    ...

def split_clusters(
    point_cloud: np.ndarray,
    labels: np.ndarray,
    unique_labels: np.ndarray,
    min_depth: int = 25,
) -> tuple[np.ndarray, np.ndarray]:
    """Apply cluster splitting to results of triplet clustering

    Triplclust has a tendency to over merge trajectories (due to colinearity near crossings). This
    post-processing algorithm aims to solve this by splitting the clusters based on a directed graph
    approach.

    Parameters
    ----------
    smoothed_cloud: numpy.ndarray
        The sorted point cloud
    labels: numpy.ndarray
        The labels generated by triplet_clustering
    unique_labels: numpy.ndarray
        The unique values in labels
    min_depth: int
        The minimum depth to use when splitting the graph. The default
        value is 25.

    Returns
    -------
    tuple[numpy.ndarray, numpy.ndarray]
        The set of 1-D integer label arrays, where the first is the set of all
        point labels and the second is the unique label values. Note that
        these may be identical to the input labels/uniques if splitting did not
        result in any changes.
    """
    ...
